#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Feb 02 13:26:51 CET 2023
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto d4a840c2c8c04e6899eb1fa52bc14900 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot TEST_FIRST_behav xil_defaultlib.TEST_FIRST -log elaborate.log"
xelab -wto d4a840c2c8c04e6899eb1fa52bc14900 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot TEST_FIRST_behav xil_defaultlib.TEST_FIRST -log elaborate.log

